In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression,ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error,root_mean_squared_error,confusion_matrix,roc_auc_score,log_loss
from sklearn.metrics import f1_score,accuracy_score,recall_score,precision_score,classification_report
from tqdm import tqdm
import os
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler,PolynomialFeatures
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
import datetime as dt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis,QuadraticDiscriminantAnalysis
from sklearn.naive_bayes import BernoulliNB,GaussianNB
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer,make_column_selector
from sklearn.tree import DecisionTreeClassifier,plot_tree,DecisionTreeRegressor
from sklearn.ensemble import BaggingClassifier,BaggingRegressor,VotingClassifier,VotingRegressor
from sklearn.metrics import accuracy_score

In [4]:
connc_data = pd.read_csv(r'../Datasets/Concrete_data.csv')
connc_data

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [11]:
X=connc_data.drop("Strength",axis=1)
y=connc_data["Strength"]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=26)

In [19]:
dtc=DecisionTreeRegressor(max_depth = 4,random_state=26)
knn = KNeighborsRegressor()
lr = LinearRegression()
el=ElasticNet()

estims = [dtc,knn, lr,el]
scores = []

for e in tqdm(estims):
    for n in [10, 15, 50, 100]:
        bagg = BaggingRegressor(random_state=26, estimator=e, n_estimators=n)
        bagg.fit(X_train, y_train)
        y_pred = bagg.predict(X_test)
        r2 = r2_score(y_test, y_pred)
        scores.append([type(e).__name__, n, r2])

df_score = pd.DataFrame(scores, columns=['estimator', 'n', 'r2_score'])
df_score.sort_values('r2_score', ascending=False)

  0%|                                                                                            | 0/4 [00:00<?, ?it/s]

 25%|█████████████████████                                                               | 1/4 [00:00<00:01,  2.05it/s]

 50%|██████████████████████████████████████████                                          | 2/4 [00:01<00:01,  1.45it/s]

 75%|███████████████████████████████████████████████████████████████                     | 3/4 [00:01<00:00,  1.81it/s]

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.86it/s]

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.80it/s]

                estimator    n  r2_score
0   DecisionTreeRegressor   10  0.783787
3   DecisionTreeRegressor  100  0.780275
1   DecisionTreeRegressor   15  0.777847
2   DecisionTreeRegressor   50  0.775496
7     KNeighborsRegressor  100  0.683729
6     KNeighborsRegressor   50  0.680985
4     KNeighborsRegressor   10  0.678554
5     KNeighborsRegressor   15  0.675296
12             ElasticNet   10  0.620164
8        LinearRegression   10  0.619629
13             ElasticNet   15  0.619367
15             ElasticNet  100  0.618955
9        LinearRegression   15  0.618851
11       LinearRegression  100  0.618434
14             ElasticNet   50  0.618041
10       LinearRegression   50  0.617486