In [54]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression,ElasticNet,LinearRegression,Lasso,Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error,root_mean_squared_error,confusion_matrix,roc_auc_score,log_loss
from sklearn.metrics import f1_score,accuracy_score,recall_score,precision_score,classification_report
from tqdm import tqdm
import os
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler,PolynomialFeatures
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
import datetime as dt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis,QuadraticDiscriminantAnalysis
from sklearn.naive_bayes import BernoulliNB,GaussianNB
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer,make_column_selector
from sklearn.tree import DecisionTreeClassifier,plot_tree,DecisionTreeRegressor
from sklearn.ensemble import BaggingClassifier,BaggingRegressor,VotingClassifier,VotingRegressor,RandomForestClassifier,RandomForestRegressor,RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.ensemble import AdaBoostClassifier, AdaBoostRegressor,GradientBoostingClassifier

In [2]:
cancer=pd.read_csv(r"../Datasets/BreastCancer.csv")
cancer

,Code,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
0,61634,5,4,3,1,2,2,2,3,1,Benign
1,63375,9,1,2,6,4,10,7,7,2,Malignant
2,76389,10,4,7,2,2,8,6,1,1,Malignant
3,95719,6,10,10,10,8,10,7,10,7,Malignant
4,128059,1,1,1,1,2,5,5,1,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...
694,1369821,10,10,10,10,5,10,10,10,7,Malignant
695,1371026,5,10,10,10,4,10,5,6,3,Malignant
696,1371920,5,1,1,1,2,1,3,2,1,Benign
697,8233704,4,1,1,1,1,1,2,1,1,Benign
698,13454352,1,1,3,1,2,1,2,1,1,Benign

In [3]:
X = cancer.drop(['Code','Class'],axis=1)
y=cancer['Class']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3,random_state=26,stratify = cancer['Class'])

In [13]:
dtc=DecisionTreeClassifier(max_depth = 1,random_state=26)
knn = KNeighborsClassifier(n_neighbors=3)
lr = LogisticRegression()
lda = LinearDiscriminantAnalysis()
nb = GaussianNB() 
ada=AdaBoostClassifier(random_state=26,estimator=dtc)
ada.fit(X_train,y_train)
y_pred_prob =ada.predict_proba(X_test)
y_pred=ada.predict(X_test)
                                                                                                                                                                                                                               
print("accuracy:",accuracy_score(y_test,y_pred))
print("log loss:",log_loss(y_test,y_pred_prob))

accuracy: 0.9619047619047619
log loss: 0.43010318673066855

In [15]:
hr = pd.read_csv(r"../Datasets/HR_comma_sep.csv")
hr

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.10,0.77,6,247,4,0,1,0,sales,low
3,0.92,0.85,5,259,5,0,1,0,sales,low
4,0.89,1.00,5,224,5,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14990,0.40,0.57,2,151,3,0,1,0,support,low
14991,0.37,0.48,2,160,3,0,1,0,support,low
14992,0.37,0.53,2,143,3,0,1,0,support,low
14993,0.11,0.96,6,280,4,0,1,0,support,low
14994,0.37,0.52,2,158,3,0,1,0,support,low

In [21]:
X = hr.drop('left',axis=1)
y=hr['left']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=hr['left'])

In [22]:
ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")
trans = ColumnTransformer(
    transformers=[("OHE", ohe,make_column_selector(dtype_include=object))],remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")
X_trn_ohe = trans.fit_transform(X_train)
X_tst_ohe = trans.transform(X_test)

In [27]:
dtc=DecisionTreeClassifier(max_depth = 1,random_state=26)
lr = LogisticRegression()
nb = GaussianNB() 
for e in [dtc,lr,nb]:
    ada=AdaBoostClassifier(random_state=26,estimator=dtc)
    ada.fit(X_trn_ohe,y_train)
    y_pred_prob =ada.predict_proba(X_tst_ohe)
    y_pred=ada.predict(X_tst_ohe)
    print("for:",e,":")                                                                                                                                                                                                                              
    print("accuracy:",accuracy_score(y_test,y_pred))
    print("log loss:",log_loss(y_test,y_pred_prob))

for: DecisionTreeClassifier(max_depth=1, random_state=26) :
accuracy: 0.948877528339631
log loss: 0.5184676494204138

for: LogisticRegression() :
accuracy: 0.948877528339631
log loss: 0.5184676494204138

for: GaussianNB() :
accuracy: 0.948877528339631
log loss: 0.5184676494204138

In [30]:


connc_data = pd.read_csv(r'../Datasets/Concrete_data.csv')
connc_data

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [32]:
X,y=connc_data.drop("Strength",axis=1),connc_data["Strength"]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=26)

In [50]:
dtc=DecisionTreeRegressor(max_depth = 1,random_state=26)
lr = LinearRegression()
en = ElasticNet(random_state=26) 
la = Lasso(random_state=26)
ri = Ridge(random_state=26)

for e in [dtc,lr,en,la,ri]:
    ada=AdaBoostRegressor(random_state=26,n_estimators=100,estimator=e)
    ada.fit(X_train,y_train)
    y_pred=ada.predict(X_test)

    print("for:",e,":")                                                                                                                                                                                                                              
    print("r2:",r2_score(y_test,y_pred))

for: DecisionTreeRegressor(max_depth=1, random_state=26) :
r2: 0.5108160242554665
for: LinearRegression() :
r2: 0.6155629770477504
for: ElasticNet(random_state=26) :
r2: 0.6173577974653357
for: Lasso(random_state=26) :
r2: 0.6188417427741009
for: Ridge(random_state=26) :
r2: 0.619511815982546

In [61]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error

n_est = [10, 25, 50, 75, 100]
rate = np.linspace(0.0001, 0.9, 30)
depth = [2, 3, 4, 5, 6]
scores = []

for n in n_est:
    for r in rate:
        for d in depth:
            gbm = GradientBoostingRegressor(random_state=26, n_estimators=n, learning_rate=r, max_depth=d)
            gbm.fit(X_train, y_train)
            y_pred = gbm.predict(X_test)
            mse = mean_squared_error(y_test, y_pred)
            scores.append([n, r, d, mse])

df_scores = pd.DataFrame(scores, columns=['n_est', 'rate', 'depth', 'score'])
df_scores = df_scores.sort_values('score')
print(df_scores.head())

     n_est      rate  depth      score
671    100  0.434534      3  21.250436
666    100  0.403503      3  22.284049
681    100  0.496597      3  22.323725
648    100  0.279379      5  22.387258
676    100  0.465566      3  22.440088

In [ ]:
df = pd.read_csv('BreastCancer.csv')
X = df.drop('Class', axis=1)
y = df['Class']

le = LabelEncoder()
y = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=y)

ohe = OneHotEncoder(sparse_output=False, drop="first").set_output(transform="pandas")
transf = ColumnTransformer(
    transformers=[("OHE", ohe, make_column_selector(dtype_include=object))],
    remainder="passthrough", verbose_feature_names_out=False).set_output(transform="pandas")

X_trn_ohe = transf.fit_transform(X_train)
X_tst_ohe = transf.transform(X_test)