In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

from sklearn.impute import SimpleImputer 

import os
os.chdir("D:/Machine_Learning/Datasets") #fetch the dataset from the folder

In [4]:
boston = pd.read_csv("Boston.csv")
X = boston.drop('medv',axis=1)
y=boston['medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [5]:
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print("R2 Score =",r2_score(y_test, y_pred))

R2 Score = 0.7467569320916589

In [8]:
lasso = Lasso()
lasso.fit(X_train, y_train)
y_pred = lasso.predict(X_test)
print("R2 Score =",r2_score(y_test, y_pred))

R2 Score = 0.7088633322868478

In [10]:
alphas=np.linspace(0.001, 5)
scores=[]

for a in alphas:
    lasso = Lasso(alpha = a)
    lasso.fit(X_train, y_train)
    y_pred = lasso.predict(X_test)
    scores.append([a, r2_score(y_test, y_pred)])
    
df_scores = pd.DataFrame(scores, columns=['alpha','score'])
df_scores.sort_values('score', ascending=False).head()

      alpha     score
0  0.001000  0.746896
3  0.307061  0.744541
2  0.205041  0.743934
4  0.409082  0.743702
1  0.103020  0.741792

In [11]:
os.chdir("D:/Machine_Learning/Cases/Concrete_Strength")

## Concrete_Strength Dataset

In [12]:
conc_data = pd.read_csv('Concrete_Data.csv')
conc_data

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [14]:
X, y = conc_data.drop('Strength', axis=1), conc_data['Strength']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [15]:
alphas=np.linspace(0.001, 5)
scores=[]

for a in alphas:
    lasso = Lasso(alpha = a)
    lasso.fit(X_train, y_train)
    y_pred = lasso.predict(X_test)
    scores.append([a, r2_score(y_test, y_pred)])
    
df_scores = pd.DataFrame(scores, columns=['alpha','score'])
df_scores.sort_values('score', ascending=False).head()

       alpha     score
23  2.347469  0.619196
24  2.449490  0.619195
22  2.245449  0.619192
25  2.551510  0.619192
21  2.143429  0.619185