In [52]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

import os
os.chdir("D:/Machine_Learning/Datasets") #fetch the dataset from the folder
os.chdir("D:/Machine_Learning/Cases/Concrete_Strength")

from sklearn.preprocessing import PolynomialFeatures

### Pizza data

In [2]:
pizza=pd.read_csv("pizza.csv")
pizza.head()

   Promote  Sales
0       23    554
1       56   1339
2       34    815
3       25    609
4       67   1600

In [17]:
X = pizza[['Promote']]  # Dataframe
y = pizza['Sales']      # Series
lr=LinearRegression()
lr.fit(X,y)
lr.coef_,lr.intercept_

(array([23.50640302]), np.float64(5.4858653632529695))

### Boston data

In [18]:
boston=pd.read_csv("Boston.csv")
boston  # medv-dependent variable

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [19]:
X = boston.drop('medv',axis=1)
y=boston['medv']

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
print("MAE =",mean_absolute_error(y_test,y_pred))
print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

MAE = 3.1527714303845022
RMSE = 4.504438687188617
R2 = 0.7467569320916589

### Polynomial  class Pizza data

In [13]:
X = pizza[['Promote']]  # Dataframe
y = pizza['Sales']      # Series

In [15]:
poly = PolynomialFeatures(degree =2, include_bias=False).set_output(transform="pandas") # include_bias=False removes the constant values
X_poly = poly.fit_transform(X)
X_poly.head()

   Promote  Promote^2
0     23.0      529.0
1     56.0     3136.0
2     34.0     1156.0
3     25.0      625.0
4     67.0     4489.0

In [16]:
lr = LinearRegression()
lr.fit(X_poly, y)
lr.coef_ , lr.intercept_
# array([ 2.48006959e+01, -1.30947333e-02]) -> x(promote)= 2.48006959e+01  x^2(promote^2)=-1.30947333e-02]

# sales = 24.8promote - -0.0130promote^2 - 18.274  (Polynomial Equation)

(array([ 2.48006959e+01, -1.30947333e-02]), np.float64(-18.27491741664585))

# polynomial tranform with 2 and 3 variables

In [10]:
insure = pd.read_csv('insure_auto.csv')
X = insure[["Home", "Automobile"]]
y = insure["Operating_Cost"]
poly = PolynomialFeatures(degree =2, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

    Home  Automobile    Home^2  Home Automobile  Automobile^2
0  400.0      1200.0  160000.0         480000.0     1440000.0
1  350.0       360.0  122500.0         126000.0      129600.0
2  600.0       800.0  360000.0         480000.0      640000.0
3  800.0      1800.0  640000.0        1440000.0     3240000.0
4  900.0      1600.0  810000.0        1440000.0     2560000.0
5  200.0      1000.0   40000.0         200000.0     1000000.0
6  120.0       900.0   14400.0         108000.0      810000.0
7  340.0      1100.0  115600.0         374000.0     1210000.0
8  490.0       900.0  240100.0         441000.0      810000.0
9  700.0       800.0  490000.0         560000.0      640000.0

In [11]:
poly = PolynomialFeatures(degree =3, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

,Home,Automobile,Home^2,Home Automobile,Automobile^2,Home^3,Home^2 Automobile,Home Automobile^2,Automobile^3
0,400.0,1200.0,160000.0,480000.0,1440000.0,64000000.0,1.920000e+08,5.760000e+08,1.728000e+09
1,350.0,360.0,122500.0,126000.0,129600.0,42875000.0,4.410000e+07,4.536000e+07,4.665600e+07
2,600.0,800.0,360000.0,480000.0,640000.0,216000000.0,2.880000e+08,3.840000e+08,5.120000e+08
3,800.0,1800.0,640000.0,1440000.0,3240000.0,512000000.0,1.152000e+09,2.592000e+09,5.832000e+09
4,900.0,1600.0,810000.0,1440000.0,2560000.0,729000000.0,1.296000e+09,2.304000e+09,4.096000e+09
5,200.0,1000.0,40000.0,200000.0,1000000.0,8000000.0,4.000000e+07,2.000000e+08,1.000000e+09
6,120.0,900.0,14400.0,108000.0,810000.0,1728000.0,1.296000e+07,9.720000e+07,7.290000e+08
7,340.0,1100.0,115600.0,374000.0,1210000.0,39304000.0,1.271600e+08,4.114000e+08,1.331000e+09
8,490.0,900.0,240100.0,441000.0,810000.0,117649000.0,2.160900e+08,3.969000e+08,7.290000e+08
9,700.0,800.0,490000.0,560000.0,640000.0,343000000.0,3.920000e+08,4.480000e+08,5.120000e+08

## Boston data

In [32]:
boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [33]:
X = boston.drop('medv',axis=1)
y=boston['medv']

In [34]:
poly = PolynomialFeatures(degree =2, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,...,tax^2,tax ptratio,tax black,tax lstat,ptratio^2,ptratio black,ptratio lstat,black^2,black lstat,lstat^2
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,...,87616.0,4528.8,117482.40,1474.08,234.09,6072.570,76.194,157529.6100,1976.5620,24.8004
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,...,58564.0,4307.6,96049.80,2211.88,316.84,7064.820,162.692,157529.6100,3627.6660,83.5396
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,...,58564.0,4307.6,95064.86,975.26,316.84,6992.374,71.734,154315.4089,1583.1049,16.2409
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,...,49284.0,4151.4,87607.86,652.68,349.69,7379.581,54.978,155732.8369,1160.2122,8.6436
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,...,49284.0,4151.4,88111.80,1183.26,349.69,7422.030,99.671,157529.6100,2115.4770,28.4089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,...,74529.0,5733.0,107013.27,2639.91,441.00,8231.790,203.070,153656.1601,3790.5433,93.5089
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,...,74529.0,5733.0,108353.70,2478.84,441.00,8334.900,190.680,157529.6100,3603.8520,82.4464
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,...,74529.0,5733.0,108353.70,1539.72,441.00,8334.900,118.440,157529.6100,2238.5160,31.8096
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,...,74529.0,5733.0,107411.85,1769.04,441.00,8262.450,136.080,154802.9025,2549.5560,41.9904
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,...,74529.0,5733.0,108353.70,2151.24,441.00,8334.900,165.480,157529.6100,3127.5720,62.0944

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.6657958510458925

In [36]:
# for degree 3

poly = PolynomialFeatures(degree =3, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = -12709.864328710943

## Housing Dataset

In [40]:
housing = pd.read_csv('Housing.csv')
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [41]:
dum_hous = pd.get_dummies(housing, dtype=int, drop_first=True)  # drop_first=True drops the one col as two cols created for yes and no
dum_hous

,price,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
0,42000.0,5850,3,1,2,1,1,0,1,0,0,0
1,38500.0,4000,2,1,1,0,1,0,0,0,0,0
2,49500.0,3060,3,1,1,0,1,0,0,0,0,0
3,60500.0,6650,3,1,2,0,1,1,0,0,0,0
4,61000.0,6360,2,1,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,0,1,1,0,0,1,0
542,94000.0,6000,3,2,4,0,1,0,0,0,1,0
543,103000.0,6000,3,2,4,1,1,1,0,0,1,0
544,105000.0,6000,3,2,2,1,1,1,0,0,1,0
545,105000.0,6000,3,1,2,1,1,0,0,0,1,0

In [42]:
X, y = dum_hous.drop('price', axis=1), dum_hous['price']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=26)

# Simple Linear regression (degree 1)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.6791781818067918

In [43]:
# for degree 2
poly = PolynomialFeatures(degree =2, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.4488658162767213

In [44]:
# for degree 3
poly = PolynomialFeatures(degree =3, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = -11.730628410247519

## Cases folder Concrete_data

In [46]:
conc_data = pd.read_csv('Concrete_Data.csv')
conc_data

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [48]:
X, y = conc_data.drop('Strength', axis=1), conc_data['Strength']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=26)

# Simple Linear regression (degree 1)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.6181464728464399

In [49]:
# for degree 2

poly = PolynomialFeatures(degree =2, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.8116988468481918

In [50]:
# for degree 3

poly = PolynomialFeatures(degree =3, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.7840101067554346

In [51]:
# for degree 4

poly = PolynomialFeatures(degree =4, include_bias=False).set_output(transform="pandas") 
X_poly = poly.fit_transform(X)
X_poly

X_train,X_test,y_train,y_test = train_test_split(X_poly, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)
# print("MAE =",mean_absolute_error(y_test,y_pred))
# print("RMSE =",root_mean_squared_error(y_test,y_pred))
print("R2 =",r2_score(y_test,y_pred))

R2 = -12.826307333608863

With degree 2 we get best performance

##