In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.metrics import recall_score, precision_score, classification_report

from sklearn.impute import SimpleImputer 

import os
os.chdir("D:/Machine_Learning/Datasets") #fetch the dataset from the folder

In [7]:
sonar = pd.read_csv('D:/Machine_Learning/Cases/Sonar/Sonar.csv')
sonar.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V52,V53,V54,V55,V56,V57,V58,V59,V60,Class
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [4]:
X , y = sonar.drop('Class', axis=1), sonar['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=26, stratify= sonar['Class'])

lr= LogisticRegression()
lr.fit(X_train, y_train)
y_pred_prob = lr.predict_proba(X_test)
y_pred = lr.predict(X_test)

In [5]:
f1_score(y_test, y_pred, average='macro')

0.8409090909090909

In [6]:
solvers = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
scores = []
for s in solvers:
    lr=LogisticRegression(solver=s)
    lr.fit(X_train, y_train)
    y_pred = lr.predict(X_test)
    scores.append([s, f1_score(y_test, y_pred, average="macro")])
df_scores = pd.DataFrame(scores, columns=['solver', 'score'])
df_scores.sort_values('score', ascending=False)

            solver     score
0            lbfgs  0.840909
2        newton-cg  0.840909
4              sag  0.840909
3  newton-cholesky  0.840909
5             saga  0.840909
1        liblinear  0.840264

In [8]:
df_scores.sort_values('score', ascending=False).iloc[0]

solver       lbfgs
score     0.840909
Name: 0, dtype: object

In [14]:
solvers = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
Cs = np.linspace(0.001, 5, 20)
scores = []
for s in solvers:
    for c in Cs:
        lr=LogisticRegression(solver=s, C=c, max_iter=500)  # max_iter=100 by default sometimes ignore it bcz it may overfit
        lr.fit(X_train, y_train)
        y_pred = lr.predict(X_test)
        scores.append([s, c, f1_score(y_test, y_pred, average="macro")])

In [15]:
df_scores = pd.DataFrame(scores, columns=['solver', 'C', 'score'])
df_scores.sort_values('score', ascending=False).iloc[0]

solver       lbfgs
C         0.790316
score     0.840909
Name: 3, dtype: object