In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss
from sklearn.preprocessing import LabelEncoder
import os
os.chdir("D:/Machine_Learning/Cases/Sonar") #fetch the dataset from the folder

In [5]:
sonar = pd.read_csv('Sonar.csv')
sonar.head(5)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V52,V53,V54,V55,V56,V57,V58,V59,V60,Class
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [6]:
le = LabelEncoder()
sonar['Class'] = le.fit_transform(sonar['Class'])

X = sonar.drop('Class', axis=1)
y = sonar['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=sonar['Class'])
le.classes_

array(['M', 'R'], dtype=object)

In [8]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred_prob = lr.predict_proba(X_test)
log_loss(y_test, y_pred_prob)
# score = roc_auc_score(y_test, y_pred_prob[:,1])
# disp = RocCurveDisplay(fpr=fpr, tpr=tpr, roc_auc=score, name="ROC Curve")
# disp.plot()
# plt.show()

0.4835944820149943

In [ ]:
solvers = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
Cs = np.linspace(0.001, 5, 20)
scores = []
for s in solvers:
    for c in Cs:
        lr=LogisticRegression(solver=s, C=c)  # max_iter=100 by default sometimes ignore it bcz it may overfit
        lr.fit(X_train, y_train)
        y_pred_prob = lr.predict_proba(X_test)
        scores.append([s, c, log_loss(y_test, y_pred_prob)])

In [13]:
df_scores = pd.DataFrame(scores, columns=['solver', 'C', 'score'])
df_scores.sort_values('score', ascending=True)

              solver         C     score
69   newton-cholesky  2.368947  0.473345
68   newton-cholesky  2.105842  0.473417
8              lbfgs  2.105842  0.473417
9              lbfgs  2.368947  0.473494
89               sag  2.368947  0.473547
..               ...       ...       ...
100             saga  0.001000  0.688419
60   newton-cholesky  0.001000  0.688419
80               sag  0.001000  0.688419
0              lbfgs  0.001000  0.688419
20         liblinear  0.001000  0.689549

[120 rows x 3 columns]