In [28]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
import os
os.chdir("D:/Machine_Learning/Datasets")

In [4]:
tel = pd.read_csv("Telecom.csv")
tel

    Gender TT_gt_100 Response
0        F         Y        N
1        M         N        N
2        M         N        N
3        F         Y        Y
4        F         N        N
..     ...       ...      ...
145      F         Y        Y
146      M         N        Y
147      M         N        N
148      M         N        N
149      F         N        N

[150 rows x 3 columns]

In [8]:
 # pd.get_dummies(housing, drop_first=True)
ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")
ohe.fit_transform(tel)
# X = dum_hous.drop('price', axis=1)
# y = dum_hous['price']

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

     Gender_M  TT_gt_100_Y  Response_Y
0         0.0          1.0         0.0
1         1.0          0.0         0.0
2         1.0          0.0         0.0
3         0.0          1.0         1.0
4         0.0          0.0         0.0
..        ...          ...         ...
145       0.0          1.0         1.0
146       1.0          0.0         1.0
147       1.0          0.0         0.0
148       1.0          0.0         0.0
149       0.0          0.0         0.0

[150 rows x 3 columns]

In [14]:
housing = pd.read_csv("Housing.csv")
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

## column transformer

In [30]:

ohe = OneHotEncoder(sparse_output=False, drop="first").set_output(transform="pandas")
scalar=StandardScaler()
trans = ColumnTransformer(
    transformers=[("OHE", ohe, ["driveway", "recroom", "fullbase", "gashw", "airco", "prefarea"]),("STD",scalar,["price","lotsize"])],remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")
trans.fit_transform(housing)

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,price,lotsize,bedrooms,bathrms,stories,garagepl
0,1.0,0.0,1.0,0.0,0.0,0.0,-0.979136,0.323028,3,1,2,1
1,1.0,0.0,0.0,0.0,0.0,0.0,-1.110329,-0.531013,2,1,1,0
2,1.0,0.0,0.0,0.0,0.0,0.0,-0.698008,-0.964958,3,1,1,0
3,1.0,1.0,0.0,0.0,0.0,0.0,-0.285686,0.692343,3,1,2,0
4,1.0,0.0,0.0,0.0,0.0,0.0,-0.266944,0.558466,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
541,1.0,1.0,0.0,0.0,1.0,0.0,0.876311,-0.161698,3,2,4,0
542,1.0,0.0,0.0,0.0,1.0,0.0,0.970020,0.392275,3,2,4,0
543,1.0,1.0,0.0,0.0,1.0,0.0,1.307374,0.392275,3,2,4,1
544,1.0,1.0,0.0,0.0,1.0,0.0,1.382342,0.392275,3,2,2,1
545,1.0,0.0,0.0,0.0,1.0,0.0,1.382342,0.392275,3,1,2,1

#### make_column_selector

In [32]:
from sklearn.compose import make_column_selector

trans = ColumnTransformer(
    transformers=[("OHE", ohe,make_column_selector(dtype_include=object))],remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")
trans.fit_transform(housing)

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,price,lotsize,bedrooms,bathrms,stories,garagepl
0,1.0,0.0,1.0,0.0,0.0,0.0,42000.0,5850,3,1,2,1
1,1.0,0.0,0.0,0.0,0.0,0.0,38500.0,4000,2,1,1,0
2,1.0,0.0,0.0,0.0,0.0,0.0,49500.0,3060,3,1,1,0
3,1.0,1.0,0.0,0.0,0.0,0.0,60500.0,6650,3,1,2,0
4,1.0,0.0,0.0,0.0,0.0,0.0,61000.0,6360,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
541,1.0,1.0,0.0,0.0,1.0,0.0,91500.0,4800,3,2,4,0
542,1.0,0.0,0.0,0.0,1.0,0.0,94000.0,6000,3,2,4,0
543,1.0,1.0,0.0,0.0,1.0,0.0,103000.0,6000,3,2,4,1
544,1.0,1.0,0.0,0.0,1.0,0.0,105000.0,6000,3,2,2,1
545,1.0,0.0,0.0,0.0,1.0,0.0,105000.0,6000,3,1,2,1