In [36]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

from sklearn.impute import SimpleImputer 

import os
os.chdir("D:/Machine_Learning/Datasets") #fetch the dataset from the folder
os.chdir("D:/Machine_Learning/Cases/Concrete_Strength")

In [37]:
boston = pd.read_csv("Boston.csv")
X = boston.drop('medv',axis=1)
y=boston['medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [35]:
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print("R2 Score =",r2_score(y_test, y_pred))

R2 Score = 0.6181464728464399

In [38]:
ridge = Ridge()
ridge.fit(X_train, y_train)
y_pred = ridge.predict(X_test)
print("R2 Score =",r2_score(y_test, y_pred))

R2 Score = 0.7443182494036571

In [39]:
ridge = Ridge(alpha=1)
ridge.fit(X_train, y_train)
y_pred = ridge.predict(X_test)
print("R2 Score =",r2_score(y_test, y_pred))

R2 Score = 0.7443182494036571

In [40]:
alphas=[0.01, 0.1, 0.5, 1, 1.5, 2.5, 5, 10]
scores=[]

for a in alphas:
    ridge = Ridge(alpha = a)
    ridge.fit(X_train, y_train)
    y_pred = ridge.predict(X_test)
    scores.append([a, r2_score(y_test, y_pred)])
    
df_scores = pd.DataFrame(scores, columns=['alpha','score'])
df_scores.sort_values('score', ascending=False)

   alpha     score
1   0.10  0.746815
0   0.01  0.746776
2   0.50  0.745805
3   1.00  0.744318
7  10.00  0.743506
4   1.50  0.743266
5   2.50  0.742176
6   5.00  0.741938

In [41]:
alphas=np.linspace(0.001, 5)
scores=[]

for a in alphas:
    ridge = Ridge(alpha = a)
    ridge.fit(X_train, y_train)
    y_pred = ridge.predict(X_test)
    scores.append([a, r2_score(y_test, y_pred)])
    
df_scores = pd.DataFrame(scores, columns=['alpha','score'])
df_scores.sort_values('score', ascending=False).head()

      alpha     score
1  0.103020  0.746813
0  0.001000  0.746759
2  0.205041  0.746663
3  0.307061  0.746405
4  0.409082  0.746097

### Concrete_Strength Dataset

In [19]:
conc_data = pd.read_csv('Concrete_Data.csv')
conc_data

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [21]:
X, y = conc_data.drop('Strength', axis=1), conc_data['Strength']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=26)

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)

print("R2 Score =",r2_score(y_test,y_pred))

R2 Score = 0.6181464728464399

In [22]:
ridge = Ridge()
ridge.fit(X_train, y_train)
y_pred = ridge.predict(X_test)
print("R2 Score =",r2_score(y_test, y_pred))

R2 Score = 0.6181470326108837

Ridge is better than linear regression

In [32]:
alphas=np.linspace(0.001, 10)
scores=[]

for a in alphas:
    ridge = Ridge(alpha = a)
    ridge.fit(X_train, y_train)
    y_pred = ridge.predict(X_test)
    scores.append([a, r2_score(y_test, y_pred)])
    
df_scores = pd.DataFrame(scores, columns=['alpha','score'])
df_scores.sort_values('score', ascending=False)

        alpha     score
49  10.000000  0.618152
48   9.795939  0.618152
47   9.591878  0.618152
46   9.387816  0.618152
45   9.183755  0.618152
44   8.979694  0.618151
43   8.775633  0.618151
42   8.571571  0.618151
41   8.367510  0.618151
40   8.163449  0.618151
39   7.959388  0.618151
38   7.755327  0.618151
37   7.551265  0.618151
36   7.347204  0.618151
35   7.143143  0.618150
34   6.939082  0.618150
33   6.735020  0.618150
32   6.530959  0.618150
31   6.326898  0.618150
30   6.122837  0.618150
29   5.918776  0.618150
28   5.714714  0.618150
27   5.510653  0.618150
26   5.306592  0.618149
25   5.102531  0.618149
24   4.898469  0.618149
23   4.694408  0.618149
22   4.490347  0.618149
21   4.286286  0.618149
20   4.082224  0.618149
19   3.878163  0.618149
18   3.674102  0.618149
17   3.470041  0.618148
16   3.265980  0.618148
15   3.061918  0.618148
14   2.857857  0.618148
13   2.653796  0.618148
12   2.449735  0.618148
11   2.245673  0.618148
10   2.041612  0.618148
9    1.837551  0.618148
8    1.633490  0.618147
7    1.429429  0.618147
6    1.225367  0.618147
5    1.021306  0.618147
4    0.817245  0.618147
3    0.613184  0.618147
2    0.409122  0.618147
1    0.205061  0.618147
0    0.001000  0.618146