In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression,ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error,root_mean_squared_error,confusion_matrix
from sklearn.metrics import f1_score,accuracy_score,recall_score,precision_score,classification_report
import os
from sklearn.preprocessing import PolynomialFeatures
import datetime as dt

In [2]:
sonar=pd.read_csv(r'../sonar.csv')
sonar

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V52,V53,V54,V55,V56,V57,V58,V59,V60,Class
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,M
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,M
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,M
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,M
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115,M

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X = sonar.drop("Class", axis=1)
y = sonar['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=y)

lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred_prob = lr.predict_proba(X_test)
print(y_pred_prob)

[[0.3554697  0.6445303 ]
 [0.59517577 0.40482423]
 [0.63761544 0.36238456]
 [0.31167323 0.68832677]
 [0.48793279 0.51206721]
 [0.5820391  0.4179609 ]
 [0.45598192 0.54401808]
 [0.22371257 0.77628743]
 [0.24161425 0.75838575]
 [0.44078779 0.55921221]
 [0.47805445 0.52194555]
 [0.78101021 0.21898979]
 [0.759551   0.240449  ]
 [0.96655141 0.03344859]
 [0.45507732 0.54492268]
 [0.60391993 0.39608007]
 [0.23738693 0.76261307]
 [0.94846746 0.05153254]
 [0.87936692 0.12063308]
 [0.25654304 0.74345696]
 [0.79070257 0.20929743]
 [0.23390137 0.76609863]
 [0.11938108 0.88061892]
 [0.74055992 0.25944008]
 [0.34111723 0.65888277]
 [0.25610192 0.74389808]
 [0.96780855 0.03219145]
 [0.91503545 0.08496455]
 [0.7295463  0.2704537 ]
 [0.60428273 0.39571727]
 [0.14413988 0.85586012]
 [0.5738057  0.4261943 ]
 [0.91290802 0.08709198]
 [0.33070988 0.66929012]
 [0.41359768 0.58640232]
 [0.26457225 0.73542775]
 [0.4640285  0.5359715 ]
 [0.8573217  0.1426783 ]
 [0.30173774 0.69826226]
 [0.79803417 0.20196583]
 [0.57864354 0.42135646]
 [0.78756915 0.21243085]
 [0.17237477 0.82762523]
 [0.19821921 0.80178079]
 [0.2078733  0.7921267 ]
 [0.5142166  0.4857834 ]
 [0.32472503 0.67527497]
 [0.96263204 0.03736796]
 [0.47549182 0.52450818]
 [0.76552358 0.23447642]
 [0.66480422 0.33519578]
 [0.7256787  0.2743213 ]
 [0.35883078 0.64116922]
 [0.66480627 0.33519373]
 [0.81623351 0.18376649]
 [0.62307777 0.37692223]
 [0.5387732  0.4612268 ]
 [0.93533821 0.06466179]
 [0.49352436 0.50647564]
 [0.28128864 0.71871136]
 [0.4261949  0.5738051 ]
 [0.69008842 0.30991158]
 [0.33851091 0.66148909]]

----------------------------------------------------------------------------------------------------------------------------------

In [4]:
a = np.array([121,3,6,2,9,43,78,2,77,34])
np.argmin(a)

np.int64(3)

In [5]:
np.argmax(y_pred_prob,axis = 1)

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1])

In [6]:
y_pred = lr.predict(X_test)
pd.crosstab(y_test,y_pred,margins=True)

col_0   M   R  All
Class
M      28   6   34
R       4  25   29
All    32  31   63

In [7]:
print(precision_score(y_test,y_pred,pos_label="M"))
print(precision_score(y_test,y_pred,pos_label="R"))

0.875
0.8064516129032258

In [8]:
print(recall_score(y_test,y_pred,pos_label="M"))
print(recall_score(y_test,y_pred,pos_label="R"))

0.8235294117647058
0.8620689655172413

In [9]:
print(f1_score(y_test,y_pred,pos_label="M"))
print(f1_score(y_test,y_pred,pos_label="R"))

0.8484848484848485
0.8333333333333334

In [10]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           M       0.88      0.82      0.85        34
           R       0.81      0.86      0.83        29

    accuracy                           0.84        63
   macro avg       0.84      0.84      0.84        63
weighted avg       0.84      0.84      0.84        63

In [11]:
y.value_counts()

Class
M    111
R     97
Name: count, dtype: int64

In [12]:
import sklearn
sklearn.__version__

'1.8.0'

In [13]:
f1_score(y_test,y_pred, average='macro')

0.8409090909090909

In [14]:
solvers = ["lbfgs", "liblinear", "newton-cg", "newton-cholesky", "sag", "saga"]

scores = []

for s in solvers:
    lr = LogisticRegression(solver=s) 
    lr.fit(X_train, y_train)
    y_pred = lr.predict(X_test)
    
    scores.append([s, f1_score(y_test, y_pred, average='macro')])

df_scores = pd.DataFrame(scores, columns=['solver', 'score'])
df_scores.sort_values('score', ascending=False)

            solver     score
0            lbfgs  0.840909
2        newton-cg  0.840909
4              sag  0.840909
3  newton-cholesky  0.840909
5             saga  0.840909
1        liblinear  0.840264

In [15]:
solvers = ["lbfgs", "liblinear", "newton-cg", "newton-cholesky", "sag", "saga"]
Cs = np.linspace(0.001,5,20)
scores = []

for c in Cs:
    # 2. The loop will now run without InvalidParameterError
    lr = LogisticRegression(solver=s,C=c,max_iter=1000) 
    lr.fit(X_train, y_train)
    y_pred = lr.predict(X_test)
    
    # 3. Append the results
    scores.append([s, f1_score(y_test, y_pred, average='macro')])

# 4. Create and display the DataFrame
df_scores = pd.DataFrame(scores, columns=['solver', 'score'])
df_scores.sort_values('score', ascending=False)

   solver     score
3    saga  0.840909
2    saga  0.840909
5    saga  0.840909
4    saga  0.840909
6    saga  0.840909
1    saga  0.839286
12   saga  0.824690
7    saga  0.824690
8    saga  0.824690
9    saga  0.824690
10   saga  0.824690
11   saga  0.824690
16   saga  0.824690
13   saga  0.824690
14   saga  0.824690
15   saga  0.824690
18   saga  0.824690
17   saga  0.824690
19   saga  0.809091
0    saga  0.350515

In [16]:
cancer=pd.read_csv(r'../Cases/Wisconsin/BreastCancer.csv')
cancer

,Code,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses,Class
0,61634,5,4,3,1,2,2,2,3,1,Benign
1,63375,9,1,2,6,4,10,7,7,2,Malignant
2,76389,10,4,7,2,2,8,6,1,1,Malignant
3,95719,6,10,10,10,8,10,7,10,7,Malignant
4,128059,1,1,1,1,2,5,5,1,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...
694,1369821,10,10,10,10,5,10,10,10,7,Malignant
695,1371026,5,10,10,10,4,10,5,6,3,Malignant
696,1371920,5,1,1,1,2,1,3,2,1,Benign
697,8233704,4,1,1,1,1,1,2,1,1,Benign
698,13454352,1,1,3,1,2,1,2,1,1,Benign

In [17]:
X,y = cancer.drop(['Code','Class'],axis=1),cancer['Class']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3,random_state=26,stratify = cancer['Class'])

solvers = ["lbfgs", "liblinear", "newton-cg", "newton-cholesky", "sag", "saga"]

scores = []

for s in solvers:
    lr = LogisticRegression(solver=s) 
    lr.fit(X_train, y_train)
    y_pred = lr.predict(X_test)
    
    scores.append([s, f1_score(y_test, y_pred, average='macro')])

df_scores = pd.DataFrame(scores, columns=['solver', 'score'])
df_scores.sort_values('score', ascending=False)

C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\PGCP-AI\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

            solver     score
0            lbfgs  0.958004
1        liblinear  0.958004
2        newton-cg  0.958004
3  newton-cholesky  0.958004
5             saga  0.958004
4              sag  0.952602

In [18]:
tst=pd.read_csv("tst_cancer.csv")
tst

,Code,Clump,UniCell_Size,Uni_CellShape,MargAdh,SEpith,BareN,BChromatin,NoemN,Mitoses
0,3444,5,4,3,1,3,2,2,3,10
1,3445,9,1,2,6,7,2,7,7,2
2,3446,9,4,8,2,2,4,6,1,1
3,3447,5,10,10,10,8,7,1,10,7
4,3448,1,10,1,1,2,5,5,1,1
5,3449,7,6,4,5,3,9,1,1,2

In [19]:
bm = LogisticRegression(solver = 'liblinear',C=0.264105)
bm.fit(X,y)
tst['Predicted']=bm.predict(tst)
tst

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Code