In [14]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.model_selection import  train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error,root_mean_squared_error
import os
from sklearn.preprocessing import PolynomialFeatures

In [15]:
os.chdir("C:/Users/PGCP-AI/Downloads/Machine-Learning-master/Machine-Learning-master")

In [16]:
Boston = pd.read_csv('Boston.csv')
Boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [17]:
X=Boston.drop("medv",axis=1)
y=Boston['medv']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=26)

In [18]:

lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
# print("MAE=",mean_absolute_error(y_test,y_pred))
# print("RMSE=",root_mean_squared_error(y_test,y_pred))
print("R2=",r2_score(y_test,y_pred))

R2= 0.7467569320916589

In [23]:
ridge=Ridge()
ridge.fit(X_train,y_train)
y_pred=ridge.predict(X_test)
print("R2=",r2_score(y_test,y_pred))

R2= 0.7443182494036571

In [22]:
ridge=Ridge(alpha=1)
ridge.fit(X_train,y_train)
y_pred=ridge.predict(X_test)
print("R2=",r2_score(y_test,y_pred))

R2= 0.7443182494036571

In [25]:
ridge=Ridge(alpha=2)
ridge.fit(X_train,y_train)
y_pred=ridge.predict(X_test)
print("R2=",r2_score(y_test,y_pred))

R2= 0.7425889301741255

In [31]:
# alphas = [0.01,0.1,0.5,1,1.5,2.5,5,10]
alphas = np.linspace(0.001,10)
scores = []
for a in alphas:
    ridge = Ridge(alpha=a)
    ridge.fit(X_train,y_train)
    y_pred=ridge.predict(X_test)
    scores.append([a,r2_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','score'])
df_scores.sort_values('score',ascending=False)

        alpha     score
0    0.001000  0.746759
1    0.205061  0.746663
2    0.409122  0.746097
3    0.613184  0.745440
4    0.817245  0.744817
5    1.021306  0.744264
6    1.225367  0.743790
49  10.000000  0.743506
48   9.795939  0.743438
7    1.429429  0.743389
47   9.591878  0.743370
46   9.387816  0.743302
45   9.183755  0.743233
44   8.979694  0.743164
43   8.775633  0.743095
8    1.633490  0.743053
42   8.571571  0.743025
41   8.367510  0.742956
40   8.163449  0.742886
39   7.959388  0.742817
9    1.837551  0.742775
38   7.755327  0.742748
37   7.551265  0.742679
36   7.347204  0.742610
10   2.041612  0.742546
35   7.143143  0.742543
34   6.939082  0.742476
33   6.735020  0.742410
11   2.245673  0.742359
32   6.530959  0.742346
31   6.326898  0.742283
30   6.122837  0.742222
12   2.449735  0.742208
29   5.918776  0.742164
28   5.714714  0.742108
13   2.653796  0.742089
27   5.510653  0.742054
26   5.306592  0.742005
14   2.857857  0.741995
25   5.102531  0.741959
15   3.061918  0.741925
24   4.898469  0.741918
23   4.694408  0.741883
16   3.265980  0.741874
22   4.490347  0.741854
17   3.470041  0.741840
21   4.286286  0.741832
18   3.674102  0.741820
20   4.082224  0.741818
19   3.878163  0.741814

## concrete_strength Dataset

In [37]:
connc_data = pd.read_csv('Concrete_data.csv')
connc_data

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [38]:
os.chdir("C:/Users/PGCP-AI/Downloads/Cases/Concrete_Strength")

In [41]:
X,y=connc_data.drop("Strength",axis=1),connc_data["Strength"]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
# print("MAE=",mean_absolute_error(y_test,y_pred))
# print("RMSE=",root_mean_squared_error(y_test,y_pred))
print("R2=",r2_score(y_test,y_pred))

R2= 0.6181464728464399

In [43]:
ridge=Ridge()
ridge.fit(X_train,y_train)
y_pred=ridge.predict(X_test)
print("R2=",r2_score(y_test,y_pred))

R2= 0.6181470326108837

In [46]:
# alphas = [0.01,0.1,0.5,1,1.5,2.5,5,10]
alphas = np.linspace(0.001,100)
scores = []
for a in alphas:
    ridge = Ridge(alpha=a)
    ridge.fit(X_train,y_train)
    y_pred=ridge.predict(X_test)
    scores.append([a,r2_score(y_test,y_pred)])
df_scores = pd.DataFrame(scores, columns=['alpha','score'])
df_scores.sort_values('score',ascending=False)

         alpha     score
49  100.000000  0.618201
48   97.959204  0.618200
47   95.918408  0.618199
46   93.877612  0.618198
45   91.836816  0.618197
44   89.796020  0.618196
43   87.755224  0.618195
42   85.714429  0.618194
41   83.673633  0.618193
40   81.632837  0.618191
39   79.592041  0.618190
38   77.551245  0.618189
37   75.510449  0.618188
36   73.469653  0.618187
35   71.428857  0.618186
34   69.388061  0.618185
33   67.347265  0.618184
32   65.306469  0.618183
31   63.265673  0.618181
30   61.224878  0.618180
29   59.184082  0.618179
28   57.143286  0.618178
27   55.102490  0.618177
26   53.061694  0.618176
25   51.020898  0.618175
24   48.980102  0.618174
23   46.939306  0.618173
22   44.898510  0.618171
21   42.857714  0.618170
20   40.816918  0.618169
19   38.776122  0.618168
18   36.735327  0.618167
17   34.694531  0.618166
16   32.653735  0.618165
15   30.612939  0.618164
14   28.572143  0.618162
13   26.531347  0.618161
12   24.490551  0.618160
11   22.449755  0.618159
10   20.408959  0.618158
9    18.368163  0.618157
8    16.327367  0.618156
7    14.286571  0.618154
6    12.245776  0.618153
5    10.204980  0.618152
4     8.164184  0.618151
3     6.123388  0.618150
2     4.082592  0.618149
1     2.041796  0.618148
0     0.001000  0.618146