In [25]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import  ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, Ridge
import os
os.chdir("D:/Machine_Learning/Datasets")

In [15]:
housing = pd.read_csv("Housing.csv")
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [16]:
X = housing.drop('price',axis=1)
y=housing['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [17]:
from sklearn.compose import make_column_selector
ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")
ohe.fit_transform(housing)
scalar=StandardScaler()
trans = ColumnTransformer(
    transformers=[("OHE", ohe,make_column_selector(dtype_include=object))],remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")
trans.fit_transform(housing)

,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes,price,lotsize,bedrooms,bathrms,stories,garagepl
0,1.0,0.0,1.0,0.0,0.0,0.0,42000.0,5850,3,1,2,1
1,1.0,0.0,0.0,0.0,0.0,0.0,38500.0,4000,2,1,1,0
2,1.0,0.0,0.0,0.0,0.0,0.0,49500.0,3060,3,1,1,0
3,1.0,1.0,0.0,0.0,0.0,0.0,60500.0,6650,3,1,2,0
4,1.0,0.0,0.0,0.0,0.0,0.0,61000.0,6360,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
541,1.0,1.0,0.0,0.0,1.0,0.0,91500.0,4800,3,2,4,0
542,1.0,0.0,0.0,0.0,1.0,0.0,94000.0,6000,3,2,4,0
543,1.0,1.0,0.0,0.0,1.0,0.0,103000.0,6000,3,2,4,1
544,1.0,1.0,0.0,0.0,1.0,0.0,105000.0,6000,3,2,2,1
545,1.0,0.0,0.0,0.0,1.0,0.0,105000.0,6000,3,1,2,1

In [23]:
X_trn_trans=trans.fit_transform(X_train)
X_tst_trans=trans.transform(X_test)

In [24]:
lr=LinearRegression()
lr.fit(X_trn_trans,y_train)
y_pred =lr.predict(X_tst_trans)
print("R2 =",r2_score(y_test,y_pred))

R2 = 0.6791781818067812

In [28]:
ridge = Ridge()
ridge.fit(X_trn_trans, y_train)
y_pred = ridge.predict(X_tst_trans)
print("R2 Score =",r2_score(y_test, y_pred))

R2 Score = 0.6784289744793978

In [30]:
tst = pd.read_csv("tst_Housing.csv")
tst

,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,5600,3,1,2,yes,no,yes,no,no,1,no
1,4355,2,1,1,yes,no,no,no,no,0,no
2,3412,3,1,1,yes,no,no,no,no,0,no
3,6666,2,2,2,yes,yes,no,no,no,0,no

In [32]:
bm=LinearRegression()
X_ohe=trans.fit_transform(X)
bm.fit(X_ohe,y)
X_ohe.columns

Index(['driveway_yes', 'recroom_yes', 'fullbase_yes', 'gashw_yes', 'airco_yes',
       'prefarea_yes', 'lotsize', 'bedrooms', 'bathrms', 'stories',
       'garagepl'],
      dtype='str')