In [66]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

from sklearn.impute import SimpleImputer 

import os
os.chdir("D:/Machine_Learning/Datasets") #fetch the dataset from the folder
# os.chdir("D:\Machine_Learning\Cases\Concrete_Strength")

### chemical dataset

In [48]:
chem = pd.read_csv("ChemicalProcess.csv")
chem

,Yield,BiologicalMaterial01,BiologicalMaterial02,BiologicalMaterial03,BiologicalMaterial04,BiologicalMaterial05,BiologicalMaterial06,BiologicalMaterial07,BiologicalMaterial08,BiologicalMaterial09,...,ManufacturingProcess36,ManufacturingProcess37,ManufacturingProcess38,ManufacturingProcess39,ManufacturingProcess40,ManufacturingProcess41,ManufacturingProcess42,ManufacturingProcess43,ManufacturingProcess44,ManufacturingProcess45
0,38.00,6.25,49.58,56.97,12.74,19.51,43.73,100.0,16.66,11.44,...,0.019,0.5,3,7.2,NaN,NaN,11.6,3.0,1.8,2.4
1,42.44,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.019,2.0,2,7.2,0.1,0.15,11.1,0.9,1.9,2.2
2,42.03,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,0.7,2,7.2,0.0,0.00,12.0,1.0,1.8,2.3
3,41.42,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,1.2,2,7.2,0.0,0.00,10.6,1.1,1.8,2.1
4,42.49,7.47,63.33,72.25,14.02,17.91,54.66,100.0,18.22,12.80,...,0.017,0.2,2,7.3,0.0,0.00,11.0,1.1,1.7,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,39.66,6.71,56.32,66.19,12.35,20.02,50.26,100.0,17.54,12.50,...,NaN,2.3,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
172,39.68,6.87,56.74,66.61,12.55,20.18,50.80,100.0,17.48,12.41,...,NaN,1.0,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
173,42.23,7.50,58.41,68.30,13.33,20.81,52.96,100.0,17.23,12.04,...,NaN,1.3,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
174,38.48,7.53,58.36,69.25,14.35,20.57,51.31,100.0,17.87,12.77,...,NaN,2.3,0,0.0,0.0,0.00,0.0,0.5,0.0,0.0
175,39.49,7.53,58.36,69.25,14.35,20.57,51.31,100.0,17.87,12.77,...,NaN,0.9,0,0.0,0.0,0.00,0.0,0.6,0.0,0.0

In [49]:
chem.isnull().sum().sum()

np.int64(106)

In [50]:
chem.shape

(176, 58)

In [51]:
chem['Yield'].isnull().sum()

np.int64(0)

In [57]:
# Perform Linear Regression by filling missing values using mean and median

In [ ]:
# Sir's way 
X = chem.drop('Yield',axis=1)
y=chem['Yield']

mean_imp = SimpleImputer(strategy='mean')
X_imp = mean_imp.fit_transform(X)

X_train,X_test,y_train,y_test = train_test_split(X_imp, y, test_size=0.3, random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)

print("R2 =",r2_score(y_test,y_pred))

In [52]:
mean_imp = SimpleImputer(strategy='mean').set_output(transform="pandas")
mean_imp.fit(chem) # Calculates mean of every column
chem1 = mean_imp.transform(chem)
chem1

,Yield,BiologicalMaterial01,BiologicalMaterial02,BiologicalMaterial03,BiologicalMaterial04,BiologicalMaterial05,BiologicalMaterial06,BiologicalMaterial07,BiologicalMaterial08,BiologicalMaterial09,...,ManufacturingProcess36,ManufacturingProcess37,ManufacturingProcess38,ManufacturingProcess39,ManufacturingProcess40,ManufacturingProcess41,ManufacturingProcess42,ManufacturingProcess43,ManufacturingProcess44,ManufacturingProcess45
0,38.00,6.25,49.58,56.97,12.74,19.51,43.73,100.0,16.66,11.44,...,0.019000,0.5,3.0,7.2,0.017714,0.023714,11.6,3.0,1.8,2.4
1,42.44,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.019000,2.0,2.0,7.2,0.100000,0.150000,11.1,0.9,1.9,2.2
2,42.03,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018000,0.7,2.0,7.2,0.000000,0.000000,12.0,1.0,1.8,2.3
3,41.42,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018000,1.2,2.0,7.2,0.000000,0.000000,10.6,1.1,1.8,2.1
4,42.49,7.47,63.33,72.25,14.02,17.91,54.66,100.0,18.22,12.80,...,0.017000,0.2,2.0,7.3,0.000000,0.000000,11.0,1.1,1.7,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,39.66,6.71,56.32,66.19,12.35,20.02,50.26,100.0,17.54,12.50,...,0.019573,2.3,0.0,0.0,0.000000,0.000000,0.0,0.6,0.0,0.0
172,39.68,6.87,56.74,66.61,12.55,20.18,50.80,100.0,17.48,12.41,...,0.019573,1.0,0.0,0.0,0.000000,0.000000,0.0,0.6,0.0,0.0
173,42.23,7.50,58.41,68.30,13.33,20.81,52.96,100.0,17.23,12.04,...,0.019573,1.3,0.0,0.0,0.000000,0.000000,0.0,0.6,0.0,0.0
174,38.48,7.53,58.36,69.25,14.35,20.57,51.31,100.0,17.87,12.77,...,0.019573,2.3,0.0,0.0,0.000000,0.000000,0.0,0.5,0.0,0.0
175,39.49,7.53,58.36,69.25,14.35,20.57,51.31,100.0,17.87,12.77,...,0.019573,0.9,0.0,0.0,0.000000,0.000000,0.0,0.6,0.0,0.0

In [53]:
chem1.isnull().sum().sum()

np.int64(0)

In [54]:
X = chem1.drop('Yield',axis=1)
y=chem1['Yield']

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)

print("R2 =",r2_score(y_test,y_pred))

R2 = -5.170497655278448

In [55]:
med_imp = SimpleImputer(strategy='median').set_output(transform="pandas")
med_imp.fit(chem) # Calculates mean of every column
chem2 = med_imp.transform(chem)
chem2

,Yield,BiologicalMaterial01,BiologicalMaterial02,BiologicalMaterial03,BiologicalMaterial04,BiologicalMaterial05,BiologicalMaterial06,BiologicalMaterial07,BiologicalMaterial08,BiologicalMaterial09,...,ManufacturingProcess36,ManufacturingProcess37,ManufacturingProcess38,ManufacturingProcess39,ManufacturingProcess40,ManufacturingProcess41,ManufacturingProcess42,ManufacturingProcess43,ManufacturingProcess44,ManufacturingProcess45
0,38.00,6.25,49.58,56.97,12.74,19.51,43.73,100.0,16.66,11.44,...,0.019,0.5,3.0,7.2,0.0,0.00,11.6,3.0,1.8,2.4
1,42.44,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.019,2.0,2.0,7.2,0.1,0.15,11.1,0.9,1.9,2.2
2,42.03,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,0.7,2.0,7.2,0.0,0.00,12.0,1.0,1.8,2.3
3,41.42,8.01,60.97,67.48,14.65,19.36,53.14,100.0,19.04,12.55,...,0.018,1.2,2.0,7.2,0.0,0.00,10.6,1.1,1.8,2.1
4,42.49,7.47,63.33,72.25,14.02,17.91,54.66,100.0,18.22,12.80,...,0.017,0.2,2.0,7.3,0.0,0.00,11.0,1.1,1.7,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,39.66,6.71,56.32,66.19,12.35,20.02,50.26,100.0,17.54,12.50,...,0.020,2.3,0.0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
172,39.68,6.87,56.74,66.61,12.55,20.18,50.80,100.0,17.48,12.41,...,0.020,1.0,0.0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
173,42.23,7.50,58.41,68.30,13.33,20.81,52.96,100.0,17.23,12.04,...,0.020,1.3,0.0,0.0,0.0,0.00,0.0,0.6,0.0,0.0
174,38.48,7.53,58.36,69.25,14.35,20.57,51.31,100.0,17.87,12.77,...,0.020,2.3,0.0,0.0,0.0,0.00,0.0,0.5,0.0,0.0
175,39.49,7.53,58.36,69.25,14.35,20.57,51.31,100.0,17.87,12.77,...,0.020,0.9,0.0,0.0,0.0,0.00,0.0,0.6,0.0,0.0

In [56]:
X = chem2.drop('Yield',axis=1)
y=chem2['Yield']

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)

print("R2 =",r2_score(y_test,y_pred))

R2 = -4.307174168501265

Median is somehow better than Mean.

### The following is the way to write above code correctly

In [63]:
X = chem.drop('Yield',axis=1)
y=chem['Yield']
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=26)

mean_imp = SimpleImputer(strategy='mean').set_output(transform="pandas")
X_trn_imp = mean_imp.fit_transform(X_train)
X_tst_imp = mean_imp.transform(X_test)

lr.fit(X_trn_imp,y_train)
y_pred =lr.predict(X_tst_imp)

print("R2 =",r2_score(y_test,y_pred))

R2 = -5.540605144298806

In [65]:
med_imp = SimpleImputer(strategy='median').set_output(transform="pandas")

X_trn_imp = med_imp.fit_transform(X_train)
X_tst_imp = med_imp.transform(X_test)

lr.fit(X_trn_imp, y_train)
y_pred =lr.predict(X_tst_imp)

print("R2 =",r2_score(y_test,y_pred))

R2 = -4.10570782574536

### job dataset

In [27]:
job = pd.read_csv("JobSalary2.csv",index_col=0)  # index_col=0 used to assign first col as index
job.isnull().sum()

Computer     2
Marketing    1
Engineer     0
dtype: int64

In [28]:
job

      Computer  Marketing  Engineer
S_No
1         84.0       55.0        75
2         90.0       53.0        70
3         63.0        NaN        88
4          NaN       50.0        77
5         63.0       41.0        89
6         75.0       54.0        85
7          NaN       51.0        96
8         77.0       64.0       105

### Constant Imputer

In [29]:
const_imp = SimpleImputer(strategy='constant', fill_value=60).set_output(transform="pandas")
const_imp.fit_transform(job)

      Computer  Marketing  Engineer
S_No
1         84.0       55.0      75.0
2         90.0       53.0      70.0
3         63.0       60.0      88.0
4         60.0       50.0      77.0
5         63.0       41.0      89.0
6         75.0       54.0      85.0
7         60.0       51.0      96.0
8         77.0       64.0     105.0

### Mean

In [30]:
job.mean()

Computer     75.333333
Marketing    52.571429
Engineer     85.625000
dtype: float64

In [31]:
mean_imp = SimpleImputer(strategy='mean').set_output(transform="pandas")
mean_imp.fit(job) # Calculates mean of every column

SimpleImputer()

In [32]:
mean_imp = SimpleImputer(strategy='mean').set_output(transform="pandas")
mean_imp.fit(job) # Calculates mean of every column
mean_imp.statistics_

array([75.33333333, 52.57142857, 85.625     ])

In [33]:
mean_imp.transform(job)

       Computer  Marketing  Engineer
S_No
1     84.000000  55.000000      75.0
2     90.000000  53.000000      70.0
3     63.000000  52.571429      88.0
4     75.333333  50.000000      77.0
5     63.000000  41.000000      89.0
6     75.000000  54.000000      85.0
7     75.333333  51.000000      96.0
8     77.000000  64.000000     105.0