In [58]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression,ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error,root_mean_squared_error,confusion_matrix,roc_auc_score,log_loss
from sklearn.metrics import f1_score,accuracy_score,recall_score,precision_score,classification_report
from tqdm import tqdm
import os
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler,PolynomialFeatures
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
import datetime as dt

from sklearn.naive_bayes import BernoulliNB,GaussianNB

### cancer

In [35]:
cancer = pd.read_csv(r'../Datasets/Cancer.csv',index_col=0)
cancer

,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat,Class
subjid,,,,,,,,,,
1,40-49,premeno,15 to 19,0 to 2,yes,three,right,left_up,no,recurrence-events
2,50-59,ge40,15 to 19,0 to 2,no,one,right,central,no,no-recurrence-events
3,50-59,ge40,35 to 39,0 to 2,no,two,left,left_low,no,recurrence-events
4,40-49,premeno,35 to 39,0 to 2,yes,three,right,left_low,yes,no-recurrence-events
5,40-49,premeno,30 to 34,3 to 5,yes,two,left,right_up,no,recurrence-events
...,...,...,...,...,...,...,...,...,...,...
282,50-59,ge40,30 to 34,6 to 8,yes,two,left,left_low,no,no-recurrence-events
283,50-59,premeno,25 to 29,3 to 5,yes,two,left,left_low,yes,no-recurrence-events
284,30-39,premeno,30 to 34,6 to 8,yes,two,right,right_up,no,no-recurrence-events
285,50-59,premeno,15 to 19,0 to 2,no,two,right,left_low,no,no-recurrence-events
286,50-59,ge40,40 to 44,0 to 2,no,three,left,right_up,no,no-recurrence-events

In [36]:
le=LabelEncoder() 
cancer['Class']=le.fit_transform(cancer['Class'])
X = cancer.drop('Class', axis=1)
y=cancer['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=26, stratify= cancer['Class'])

In [37]:
from sklearn.compose import make_column_selector,ColumnTransformer
ohe=OneHotEncoder(sparse_output=False,drop="first",handle_unknown="ignore").set_output(transform="pandas")
X_trn_ohe = ohe.fit_transform(X_train)
X_tst_ohe = ohe.transform(X_test)

In [38]:
nb = BernoulliNB()
nb.fit(X_trn_ohe,y_train)
y_pred_prob = nb.predict_proba(X_tst_ohe)
print("ROC AUC=",roc_auc_score(y_test, y_pred_prob[:,1]))
y_pred =nb.predict(X_tst_ohe)   
print("ACURACY_SCORE =",accuracy_score(y_test,y_pred))

ROC AUC= 0.6958333333333333
ACURACY_SCORE = 0.7093023255813954

In [41]:
loss=log_loss(y_test,y_pred_prob)
loss

0.6125590570850347

### telecom

In [53]:
telecom = pd.read_csv(r'../Datasets/Telecom.csv')
telecom

    Gender TT_gt_100 Response
0        F         Y        N
1        M         N        N
2        M         N        N
3        F         Y        Y
4        F         N        N
..     ...       ...      ...
145      F         Y        Y
146      M         N        Y
147      M         N        N
148      M         N        N
149      F         N        N

[150 rows x 3 columns]

In [54]:
le=LabelEncoder() 
telecom['Response']=le.fit_transform(telecom['Response'])
X = telecom.drop('Response', axis=1)
y=telecom['Response']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=26, stratify= telecom['Response'])

In [55]:
from sklearn.compose import make_column_selector,ColumnTransformer
ohe=OneHotEncoder(sparse_output=False,drop="first",handle_unknown="ignore").set_output(transform="pandas")
X_trn_ohe = ohe.fit_transform(X_train)
X_tst_ohe = ohe.transform(X_test)

In [56]:
nb = BernoulliNB()
nb.fit(X_trn_ohe,y_train)
y_pred_prob = nb.predict_proba(X_tst_ohe)
print("ROC AUC=",roc_auc_score(y_test, y_pred_prob[:,1]))
y_pred =nb.predict(X_tst_ohe)   
print("ACURACY_SCORE =",accuracy_score(y_test,y_pred))

ROC AUC= 0.9140316205533597
ACURACY_SCORE = 0.9111111111111111

In [57]:
loss=log_loss(y_test,y_pred_prob)
loss

0.3556173959937359