In [28]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression,ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error,root_mean_squared_error,confusion_matrix,roc_auc_score,log_loss
from sklearn.metrics import f1_score,accuracy_score,recall_score,precision_score,classification_report
import os
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler,PolynomialFeatures
from sklearn.neighbors import KNeighborsClassifier
import datetime as dt

In [41]:
sonar = pd.read_csv(r"../Datasets/sonar.csv")
sonar

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V52,V53,V54,V55,V56,V57,V58,V59,V60,Class
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,M
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,M
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,M
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,M
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115,M

In [42]:
sonar['Class']

0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: Class, Length: 208, dtype: str

In [45]:
le=LabelEncoder() 
sonar['Class']=le.fit_transform(sonar['Class'])
sonar['Class']

0      1
1      1
2      1
3      1
4      1
      ..
203    0
204    0
205    0
206    0
207    0
Name: Class, Length: 208, dtype: int64

In [1]:
X = sonar.drop('Class', axis=1)
print(X)
y = sonar['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=26, stratify= sonar['Class'])

NameError: name 'sonar' is not defined

In [2]:
knn= KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train, y_train)
y_pred_prob = knn.predict_proba(X_test)
y_pred = knn.predict(X_test)
y_pred_prob = knn.predict_proba(X_test)
roc_auc_score(y_test, y_pred_prob[:,1])

NameError: name 'KNeighborsClassifier' is not defined

In [6]:
ks=[1,2,3,4,5,6,7,8,9,10]
scores = []
for k in ks:
    knn= KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred_prob = knn.predict_proba(X_test)
    scores.append([k, roc_auc_score(y_test, y_pred_prob[:,1])])
df_scores = pd.DataFrame(scores, columns=['ks', 'score'])
df_scores.sort_values('score', ascending=False)

   ks     score
1   2  0.892495
2   3  0.881846
3   4  0.869168
4   5  0.845335
5   6  0.831643
6   7  0.809331
0   1  0.808316
7   8  0.790568
8   9  0.785497
9  10  0.761156

In [7]:
hr = pd.read_csv(r"../Datasets/HR_comma_sep.csv")
hr

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.10,0.77,6,247,4,0,1,0,sales,low
3,0.92,0.85,5,259,5,0,1,0,sales,low
4,0.89,1.00,5,224,5,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...,...
14990,0.40,0.57,2,151,3,0,1,0,support,low
14991,0.37,0.48,2,160,3,0,1,0,support,low
14992,0.37,0.53,2,143,3,0,1,0,support,low
14993,0.11,0.96,6,280,4,0,1,0,support,low
14994,0.37,0.52,2,158,3,0,1,0,support,low

In [8]:
le=LabelEncoder() 
hr['left']=le.fit_transform(hr['left'])
X = hr.drop('left',axis=1)
y=hr['left']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26, stratify=hr['left'])

In [9]:
from sklearn.compose import make_column_selector,ColumnTransformer

ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")
trans = ColumnTransformer(
    transformers=[("OHE", ohe,make_column_selector(dtype_include=object))],remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")

In [10]:
X_trn_ohe = trans.fit_transform(X_train)
X_tst_ohe = trans.transform(X_test)

In [11]:
ks=[1,2,3,4,5,6,7,8,9,10]
scores = []
for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_trn_ohe, y_train)
    y_pred_prob = knn.predict_proba(X_tst_ohe)
    scores.append([k, roc_auc_score(y_test, y_pred_prob[:,1])])
df_scores = pd.DataFrame(scores, columns=['ks', 'score'])
df_scores.sort_values('score', ascending=False)

   ks     score
7   8  0.973812
8   9  0.973488
6   7  0.973273
9  10  0.972681
5   6  0.972560
4   5  0.971581
3   4  0.970761
2   3  0.967524
1   2  0.963435
0   1  0.951201

In [14]:
image = pd.read_csv(r"../Datasets/Image_Segmentation.csv")
image

,Class,region.centroid.col,region.centroid.row,region.pixel.count,short.line.density.5,short.line.density.2,vedge.mean,vegde.sd,hedge.mean,hedge.sd,intensity.mean,rawred.mean,rawblue.mean,rawgreen.mean,exred.mean,exblue.mean,exgreen.mean,value.mean,saturation.mean,hue-mean
0,BRICKFACE,188,133,9,0.000000,0.0,0.333333,0.266667,0.500000,0.077778,6.666666,8.333334,7.777778,3.888889,5.000000,3.333333,-8.333333,8.444445,0.538580,-0.924817
1,BRICKFACE,105,139,9,0.000000,0.0,0.277778,0.107407,0.833333,0.522222,6.111111,7.555555,7.222222,3.555556,4.333334,3.333333,-7.666666,7.555555,0.532628,-0.965946
2,BRICKFACE,34,137,9,0.000000,0.0,0.500000,0.166667,1.111111,0.474074,5.851852,7.777778,6.444445,3.333333,5.777778,1.777778,-7.555555,7.777778,0.573633,-0.744272
3,BRICKFACE,39,111,9,0.000000,0.0,0.722222,0.374074,0.888889,0.429629,6.037037,7.000000,7.666666,3.444444,2.888889,4.888889,-7.777778,7.888889,0.562919,-1.175773
4,BRICKFACE,16,128,9,0.000000,0.0,0.500000,0.077778,0.666667,0.311111,5.555555,6.888889,6.666666,3.111111,4.000000,3.333333,-7.333334,7.111111,0.561508,-0.985811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,GRASS,36,243,9,0.111111,0.0,1.888889,1.851851,2.000000,0.711110,13.333333,9.888889,12.111111,18.000000,-10.333333,-3.666667,14.000000,18.000000,0.452229,2.368311
205,GRASS,186,218,9,0.000000,0.0,1.166667,0.744444,1.166667,0.655555,13.703704,10.666667,12.666667,17.777779,-9.111111,-3.111111,12.222222,17.777779,0.401347,2.382684
206,GRASS,197,236,9,0.000000,0.0,2.444444,6.829628,3.333333,7.599998,16.074074,13.111111,16.666668,18.444445,-8.888889,1.777778,7.111111,18.555555,0.292729,2.789800
207,GRASS,208,240,9,0.111111,0.0,1.055556,0.862963,2.444444,5.007407,14.148149,10.888889,13.000000,18.555555,-9.777778,-3.444444,13.222222,18.555555,0.421621,2.392487
208,GRASS,223,185,9,0.000000,0.0,0.500000,0.349603,2.388889,2.080776,12.962963,11.555555,9.777778,17.555555,-4.222222,-9.555555,13.777778,17.555555,0.445418,1.838850

In [16]:
le=LabelEncoder() 
image['Class']=le.fit_transform(image['Class'])
X = image.drop('Class', axis=1)
y=image['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=26, stratify= image['Class'])

In [17]:
from sklearn.compose import make_column_selector,ColumnTransformer

ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")
trans = ColumnTransformer(
    transformers=[("OHE", ohe,make_column_selector(dtype_include=object))],remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")

In [18]:
X_trn_ohe = trans.fit_transform(X_train)
X_tst_ohe = trans.transform(X_test)

In [19]:
ks=[1,2,3,4,5,6,7,8,9,10]
scores = []
for k in ks:
    knn= KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_trn_ohe, y_train)
    y_pred_prob = knn.predict_proba(X_tst_ohe)
    scores.append([k, log_loss(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['ks', 'log_loss'])
df_scores.sort_values('log_loss', ascending=False)

   ks  log_loss
0   1  4.004850
1   2  3.036645
3   4  2.015082
2   3  1.996419
4   5  1.506703
9  10  1.084273
8   9  1.049631
7   8  1.016964
6   7  0.981489
5   6  0.971258

### with standard scaling

In [22]:
scalar=StandardScaler().set_output(transform="pandas")
scalar.fit(X_train)
X_trn_scl=scalar.transform(X_train)
X_tst_scl=scalar.transform(X_test)

In [26]:
ks=[1,2,3,4,5,6,7,8,9,10]
scores = []
for k in ks:
    knn= KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred_prob = knn.predict_proba(X_tst_scl)
    scores.append([k, log_loss(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['ks', 'log_loss'])
df_scores.sort_values('log_loss', ascending=False)

   ks  log_loss
0   1  4.004850
1   2  3.465736
4   5  1.322391
3   4  1.301800
2   3  1.257178
6   7  0.856190
5   6  0.815084
9  10  0.399369
8   9  0.381166
7   8  0.352821

### max scaling

In [29]:
scalar=MinMaxScaler().set_output(transform="pandas")
scalar.fit(X_train)
X_trn_scl=scalar.transform(X_train)
X_tst_scl=scalar.transform(X_test)

In [33]:
scalar

MinMaxScaler()

In [1]:
ks=[1,2,3,4,5,6,7,8,9,10]
scores = []
for k in ks:
    knn= KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred_prob = knn.predict_proba(X_tst_scl)
    scores.append([k, log_loss(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['ks', 'log_loss'])
df_scores.sort_values('log_loss', ascending=False)

NameError: name 'KNeighborsClassifier' is not defined

In [2]:
knn= KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train, y_train)
y_pred_prob = knn.predict_proba(X_test)
y_pred = knn.predict(X_test)
y_pred_prob = knn.predict_proba(X_test)
roc_auc_score(y_test, y_pred_prob[:,1])

In [1]:
ks=[1,2,3,4,5,6,7,8,9,10]
scores = []
for k in ks:
    knn= KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred_prob = knn.predict_proba(X_tst_scl)
    scores.append([k, log_loss(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['ks', 'log_loss'])
df_scores.sort_values('log_loss', ascending=False)