In [24]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression,ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error,root_mean_squared_error,confusion_matrix,roc_auc_score,log_loss
from sklearn.metrics import f1_score,accuracy_score,recall_score,precision_score,classification_report
import os
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor

import datetime as dt

In [5]:
Boston = pd.read_csv(r"../Datasets/Boston.csv")
Boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [21]:
scalar=StandardScaler().set_output(transform="pandas")
scalar.fit(X_train)
X_trn_scl=scalar.transform(X_train)
X_tst_scl=scalar.transform(X_test)

In [29]:
ks=[1,2,3,4,5,6,7,8,9,10]
scores = []
for k in ks:
    knn= KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred_prob = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['ks', 'r2_score'])
df_scores.sort_values('r2_score', ascending=False)

   ks  r2_score
4   5  0.720809
3   4  0.720349
1   2  0.720333
8   9  0.708297
5   6  0.705555
2   3  0.704720
7   8  0.701514
6   7  0.701001
9  10  0.698105
0   1  0.691733

### minmax

In [31]:
scalar=MinMaxScaler().set_output(transform="pandas")
scalar.fit(X_train)
X_trn_scl=scalar.transform(X_train)
X_tst_scl=scalar.transform(X_test)

In [32]:
ks=[1,2,3,4,5,6,7,8,9,10]
scores = []
for k in ks:
    knn= KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred_prob = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred_prob)])
df_scores = pd.DataFrame(scores, columns=['ks', 'r2_score'])
df_scores.sort_values('r2_score', ascending=False)

   ks  r2_score
2   3  0.713301
3   4  0.711778
4   5  0.704968
1   2  0.692504
5   6  0.677821
0   1  0.675963
6   7  0.655112
7   8  0.639558
8   9  0.633555
9  10  0.627269